#!/usr/bin/env python3
"""
Regenerate config/runtimes.yaml from ~/.agentic-os/config.json.

The checked-in file names C:/Users/ankur.singh paths that do not exist on this
machine -- it was copied from a second engineer's setup and never localised.
Agent OS already records the correct local binaries, so we read them rather
than hand-editing and letting the two disagree again.

    python tools/localize_runtimes.py --check    # report, change nothing
    python tools/localize_runtimes.py --write    # rewrite runtimes.yaml

Safety
    --check never writes. --write replaces the whole file, which is safe
    because the file is generated: every value is derived from Agent OS
    config or PATH.
"""
import json, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTIC = Path.home() / ".agentic-os" / "config.json"
OUT = ROOT / "config" / "runtimes.yaml"

# name -> (agentic-os config key, cmd_template, extra keys)
SPEC = {
    "hermes":   ("hermes",   ["-p", "{profile}", "--prompt-file", "{instruction_file}"], {}),
    "openclaw": ("openclaw", ["--agent", "{agent}", "--prompt-file", "{instruction_file}"], {}),
    "opencode": (None,       ["run", "{message}", "-m", "{model}"], {"strip_ansi": True}),
    "claude":   ("claude",   ["-p", "{instruction}", "--model", "{model}"], {}),
    "python":   (None,       [], {}),
}


def resolve(name, key):
    """Agent OS config first, then PATH. Returns a forward-slashed absolute path or None."""
    if key and AGENTIC.is_file():
        try:
            v = json.loads(AGENTIC.read_text(encoding="utf-8")).get(key)
            if v and Path(v).exists():
                return str(Path(v)).replace("\\", "/")
        except Exception:
            pass
    if name == "python":
        return sys.executable.replace("\\", "/")
    w = shutil.which(name)
    return str(Path(w).resolve()).replace("\\", "/") if w else None


def version_of(binpath):
    """First line of `--version`, folded to ASCII.

    Hermes prints a U+00B7 separator which arrives here as mojibake under the
    Windows console codec. Anything non-ASCII in a generated config is a
    liability -- setup.py already ascii-folds for the same reason -- so the
    version string is reduced to characters that survive every codec.
    """
    try:
        r = subprocess.run([binpath, "--version"], capture_output=True, text=True, timeout=30)
        blob = (r.stdout or r.stderr or "").strip()
        if not blob:
            return ""
        line = blob.splitlines()[0]
        return line.encode("ascii", "ignore").decode("ascii").replace('"', "").strip()
    except Exception:
        return ""


def build():
    lines = [
        "# Command templates. GENERATED by tools/localize_runtimes.py - do not hand-edit.",
        "# Absolute paths only: the name on PATH may be a shim (decision D-015).",
        "runtimes:",
    ]
    missing = []
    for name, (key, tmpl, extra) in SPEC.items():
        b = resolve(name, key)
        if not b:
            missing.append(name)
            continue
        lines.append(f"  {name}:")
        lines.append(f"    bin: {b}")
        lines.append('    version_flag: "--version"')
        v = version_of(b)
        if v:
            lines.append(f'    expected_version: "{v}"')
        if tmpl:
            lines.append(f"    cmd_template: {json.dumps(tmpl)}")
        for k, val in extra.items():
            lines.append(f"    {k}: {str(val).lower()}")
    return "\n".join(lines) + "\n", missing


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    text, missing = build()
    for m in missing:
        print(f"  [!] {m}: not found in ~/.agentic-os/config.json or on PATH")
    if mode == "--write":
        OUT.write_text(text, encoding="utf-8")
        print(f"  [ok] wrote {OUT}")
    else:
        print(text)
    sys.exit(1 if missing else 0)
