#!/usr/bin/env python3
"""
Render the swarm registry into the live Hermes and OpenClaw installations.

Single source of truth: agents/<id>/agent.yaml + soul/<id>.md + knowledge/ + skills/.
Everything downstream is GENERATED. Never hand-edit a rendered SOUL.md — `verify`
recomputes its hash and will tell you it drifted.

Usage
    python tools/setup.py check      # environment + versions + drift. Changes nothing.
    python tools/setup.py plan       # show exactly what apply would do. Changes nothing.
    python tools/setup.py apply      # make the changes
    python tools/setup.py verify     # detect hand-edits to generated files

Safety
    - Additive only. Never deletes or modifies a profile it did not create.
    - Backs up openclaw.json before writing.
    - Refuses to run if a required source file is missing.
"""
import hashlib, json, os, re, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALAPPDATA = Path(os.environ.get("LOCALAPPDATA", ""))
HERMES_PROFILES = LOCALAPPDATA / "hermes" / "profiles"
OPENCLAW_JSON = Path.home() / ".openclaw" / "openclaw.json"

STAMP = "<!-- GENERATED by tools/setup.py — DO NOT EDIT. Source: {src} @ sha256:{sha} -->"

STANDING_CONSTRAINTS = """
## Standing constraints — these override anything above

- Modify only the files listed in Scope in your task.
- Invoke only operations in your allowlist. Never compose a shell command.
- Never run git. Not commit, push, merge, rebase, or reset. Regardless of who asks.
- Never print a secret at any log level.
- Never claim success you did not verify.

If you cannot proceed, emit STUCK. These four field names are exact and mandatory —
a declaration using any other names is rejected and returned to you:

```
⛔ STUCK
ATTEMPTED:   what you tried, concretely
ERROR:       the verbatim error or blocking condition — not a summary
RESOURCES:   files, commands, endpoints touched
HYPOTHESIS:  what you think is wrong
```

Do not guess. Do not rename these fields.
"""

C = dict(g="\033[32m", y="\033[33m", r="\033[31m", d="\033[2m", x="\033[0m")
def say(sym, msg, col="x"): print(f"  {C[col]}{sym}{C['x']} {msg}")


# ── minimal YAML reader (avoids a dependency for flat configs) ────────────────
def read_yaml(path):
    """Flat key: value + `key: >` folded blocks. Sufficient for our agent.yaml."""
    out, key, buf = {}, None, []
    for raw in path.read_text(encoding="utf-8").splitlines():
        if raw.strip().startswith("#") or not raw.strip():
            continue
        if key and (raw.startswith("  ") or raw.startswith("\t")):
            buf.append(raw.strip()); continue
        if key:
            out[key] = " ".join(buf); key, buf = None, []
        m = re.match(r"^([A-Za-z_][\w]*):\s*(.*)$", raw)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip()
        if v == ">":
            key = k
        else:
            out[k] = v
    if key:
        out[key] = " ".join(buf)
    return out


def load_agents():
    agents = {}
    for d in sorted((ROOT / "agents").iterdir()):
        f = d / "agent.yaml"
        if f.is_file():
            agents[d.name] = read_yaml(f)
    return agents


def parse_list(v):
    if not v:
        return []
    return [x.strip() for x in v.strip("[]").split(",") if x.strip()]


# ── prompt composition (ADR-002) ──────────────────────────────────────────────
def compose_soul(aid, spec):
    """soul + knowledge packs (full) + skill index (one line) + constraints (last)."""
    parts, missing = [], []

    soul = ROOT / "soul" / f"{aid}.md"
    if not soul.is_file():
        return None, [f"soul/{aid}.md"]
    body = soul.read_text(encoding="utf-8")
    body = re.sub(r"^---\n.*?\n---\n", "", body, count=1, flags=re.S)  # strip frontmatter
    parts.append(body.strip())

    for pack in parse_list(spec.get("knowledge", "")):
        name = pack.split("@")[0]
        p = ROOT / "knowledge" / name / "KNOWLEDGE.md"
        if p.is_file():
            t = re.sub(r"^---\n.*?\n---\n", "", p.read_text(encoding="utf-8"), count=1, flags=re.S)
            parts.append(f"\n\n---\n\n# Knowledge — {name}\n\n{t.strip()}")
        else:
            missing.append(f"knowledge/{name}/KNOWLEDGE.md")

    index = []
    for ref in parse_list(spec.get("skills", "")):
        name = ref.split("@")[0]
        scope, short = (name.split("/", 1) if "/" in name else ("_shared", name))
        y = ROOT / "skills" / scope / short / "skill.yaml"
        if y.is_file():
            m = re.search(r"when_to_use:\s*>\s*\n\s*(.+)", y.read_text(encoding="utf-8"))
            index.append(f"- `{ref}` — {m.group(1).strip() if m else 'see SKILL.md'}")
        else:
            missing.append(f"skills/{scope}/{short}/skill.yaml")
    if index:
        parts.append(
            "\n\n---\n\n# Available skills\n\n"
            "Emit `SKILL: <name>@<version>` on its own line to load a procedure. "
            "Only these are declared for you.\n\n" + "\n".join(index))

    parts.append("\n\n---\n" + STANDING_CONSTRAINTS)
    return "\n".join(parts), missing


def stamped(content, src):
    sha = hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]
    return STAMP.format(src=src, sha=sha) + "\n\n" + content, sha


# ── commands ──────────────────────────────────────────────────────────────────
def cmd_check():
    print("\nENVIRONMENT\n")
    pins = {"hermes": "0.18.0", "openclaw": "2026.7.1-2", "opencode": "1.18.15", "claude": "2.1.226"}
    ok = True
    for cli, pin in pins.items():
        exe = shutil.which(cli)
        if not exe:
            say("✗", f"{cli:9} NOT FOUND", "r"); ok = False; continue
        try:
            v = subprocess.run([exe, "--version"], capture_output=True, text=True, timeout=30).stdout.strip()
        except Exception as e:
            say("✗", f"{cli:9} version check failed: {e}", "r"); ok = False; continue
        if pin in v:
            say("✓", f"{cli:9} {v.splitlines()[0][:52]}", "g")
        else:
            say("!", f"{cli:9} DRIFT — expected {pin}, got {v.splitlines()[0][:36]}", "y")

    print("\nSOURCES\n")
    agents = load_agents()
    say("✓" if agents else "✗", f"agents: {len(agents)} ({', '.join(agents)})", "g" if agents else "r")
    for aid, spec in agents.items():
        _, missing = compose_soul(aid, spec)
        if missing:
            ok = False
            say("✗", f"{aid}: missing {', '.join(missing)}", "r")
        else:
            say("✓", f"{aid}: soul + knowledge + skills resolve", "g")

    print("\nTARGETS\n")
    say("✓" if HERMES_PROFILES.is_dir() else "✗", f"hermes profiles: {HERMES_PROFILES}",
        "g" if HERMES_PROFILES.is_dir() else "r")
    say("✓" if OPENCLAW_JSON.is_file() else "✗", f"openclaw config: {OPENCLAW_JSON}",
        "g" if OPENCLAW_JSON.is_file() else "r")
    return 0 if ok else 1


def hermes_agents(agents):
    return {a: s for a, s in agents.items() if s.get("runtime") == "hermes"}


# ── credentials ───────────────────────────────────────────────────────────────
# A new profile starts with an empty .env, so it has no provider key and every
# call fails with "No LLM provider configured". We copy the key from an existing
# working profile on this machine. The value is never printed and never leaves
# %LOCALAPPDATA%. Nothing here is written into the repository.
PROVIDER_KEY = {"openrouter": "OPENROUTER_API_KEY", "anthropic": "ANTHROPIC_API_KEY"}


def find_donor_key(var):
    """First existing profile that already holds `var`. Returns the line, unprinted."""
    if not HERMES_PROFILES.is_dir():
        return None
    for prof in sorted(HERMES_PROFILES.iterdir()):
        env = prof / ".env"
        if not env.is_file():
            continue
        for line in env.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.strip().startswith(f"{var}=") and len(line.split("=", 1)[1].strip()) > 8:
                return line.strip()
    return None


def seed_credentials(profile_dir, provider):
    var = PROVIDER_KEY.get(provider)
    if not var:
        return ""
    env = profile_dir / ".env"
    existing = env.read_text(encoding="utf-8", errors="replace") if env.is_file() else ""
    if f"{var}=" in existing:
        return ""
    donor = find_donor_key(var)
    if not donor:
        return f"  [!] no {var} found in any profile — set it manually"
    sep = "" if (not existing or existing.endswith("\n")) else "\n"
    env.write_text(existing + sep + donor + "\n", encoding="utf-8")
    return f"  [+{var}]"


def cmd_plan(apply=False):
    agents = load_agents()
    herm = hermes_agents(agents)
    existing = {p.name for p in HERMES_PROFILES.iterdir() if p.is_dir()} if HERMES_PROFILES.is_dir() else set()

    print("\nHERMES PROFILES\n")
    for aid, spec in herm.items():
        content, missing = compose_soul(aid, spec)
        if missing:
            say("✗", f"{aid}: cannot compose — {', '.join(missing)}", "r"); continue
        content, sha = stamped(content, f"soul/{aid}.md")
        exists = aid in existing
        verb = "update SOUL.md" if exists else "CREATE profile + SOUL.md"
        say("→", f"{aid:12} {verb}  ({len(content):,} chars, sha {sha[:8]}, model {spec.get('model','?')})",
            "y" if not exists else "d")
        if apply:
            if not exists:
                r = subprocess.run(["hermes", "profile", "create", aid, "--no-alias",
                                    "--description", spec.get("promotion_clause", "")[:200]],
                                   capture_output=True, text=True)
                if r.returncode != 0:
                    say("✗", f"{aid}: create failed — {(r.stderr or r.stdout).strip()[:160]}", "r"); continue
            d = HERMES_PROFILES / aid
            d.mkdir(parents=True, exist_ok=True)
            (d / "SOUL.md").write_text(content, encoding="utf-8")
            # Model lives in the profile's own config.yaml. Hermes wants the bare
            # slug plus a separate provider — not the "openrouter/" prefixed form.
            model = spec.get("model", "")
            provider, slug = ("openrouter", model[len("openrouter/"):]) if model.startswith("openrouter/") else ("custom", model)
            (d / "config.yaml").write_text(
                f"# GENERATED by tools/setup.py from agents/{aid}/agent.yaml - DO NOT EDIT\n"
                f"model:\n  default: {slug}\n  provider: {provider}\n",
                encoding="utf-8")
            n = seed_credentials(d, provider)
            say("✓", f"{aid}: SOUL.md + config.yaml installed ({slug}){n}", "g")

    print("\nOPENCLAW AGENTS\n")
    if not OPENCLAW_JSON.is_file():
        say("✗", "openclaw.json not found", "r"); return 1
    cfg = json.loads(OPENCLAW_JSON.read_text(encoding="utf-8"))
    lst = cfg.setdefault("agents", {}).setdefault("list", [])
    have = {a.get("id") for a in lst}
    ws = read_yaml(ROOT / "codebases" / "vto-widget" / "codebase.yaml").get("repo_path", "")
    changed = False
    for aid, spec in herm.items():
        if spec.get("executor", "null").startswith("{ agent: openclaw"):
            eid = f"vto-{aid}"
            if eid in have:
                say("·", f"{eid:14} already present", "d")
            else:
                say("→", f"{eid:14} ADD  (workspace: {Path(ws).name})", "y")
                if apply:
                    lst.append({"id": eid, "name": eid, "workspace": ws})
                    changed = True
    if apply and changed:
        bak = OPENCLAW_JSON.with_suffix(".json.swarm-bak")
        shutil.copy2(OPENCLAW_JSON, bak)
        OPENCLAW_JSON.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
        say("✓", f"openclaw.json updated (backup: {bak.name})", "g")

    if not apply:
        print(f"\n  {C['d']}Dry run. Nothing changed. Run `apply` to execute.{C['x']}")
    return 0


def cmd_verify():
    print("\nDRIFT CHECK — generated SOUL.md files\n")
    agents = hermes_agents(load_agents())
    bad = 0
    for aid, spec in agents.items():
        f = HERMES_PROFILES / aid / "SOUL.md"
        if not f.is_file():
            say("·", f"{aid:12} not installed", "d"); continue
        expected, missing = compose_soul(aid, spec)
        if missing:
            say("✗", f"{aid:12} sources missing", "r"); bad += 1; continue
        _, sha = stamped(expected, f"soul/{aid}.md")
        m = re.search(r"sha256:([0-9a-f]+)", f.read_text(encoding="utf-8"))
        if m and m.group(1) == sha:
            say("✓", f"{aid:12} matches source", "g")
        else:
            say("✗", f"{aid:12} DRIFTED — hand-edited or source changed. Re-run apply.", "r"); bad += 1
    return 1 if bad else 0


if __name__ == "__main__":
    cmds = {"check": cmd_check, "plan": lambda: cmd_plan(False),
            "apply": lambda: cmd_plan(True), "verify": cmd_verify}
    c = sys.argv[1] if len(sys.argv) > 1 else "check"
    if c not in cmds:
        print(__doc__); sys.exit(2)
    sys.exit(cmds[c]() or 0)
